### ISSUE TITLE
400 Invalid JSON payload while sending an image message to Google Gemini 1.5 model

### ISSUE THREAD

**Issue by nimish-gupta** [braintrustdata/braintrust-proxy#103]
### Description
We encountered an issue when sending an image as part of a message to the **Google Gemini 1.5 Flash model** using the Braintrust Proxy. The request fails with the following error:
```
400 Invalid JSON payload received. 
Unknown name "text" at 'contents[1].parts[0]': Proto field is not repeating, cannot start list.
```

### Steps to Reproduce:
1. Set up the Braintrust Proxy with Google Gemini 1.5 Flash API using the following code snippet:
```
const client = new OpenAI({
  baseURL: "https://api.braintrust.dev/v1/proxy",
  apiKey: process.env.BRAINTRUST_API_KEY,
});

const response = await client.chat.completions.create({
  model: "gemini-1.5-flash-latest",
  messages: [
    { role: "user", content: "What do you think of this image?" },
    { role: "user", content: { type: "image_url", image_url: { url: "https://example.com/image.jpg" } } }
  ],
});
console.log(response);

```
2. The request fails with the 400 error mentioned above.

### Expected Behaviour:
1. The message containing the image should be processed successfully by the Gemini 1.5 Flash model via the Braintrust Proxy.
2. The API should return a valid response describing the image or engaging with the user prompt accordingly.

### Impact:
1. This issue blocks us from sending media (specifically images) along with text messages to the Gemini 1.5 model.
2. It is affecting the functionality needed for applications involving image and text-based conversation flows.

**Comment by ankrgyl** [comment]
Looks like you might be missing an array around the second `content` block, i.e.

```
    { role: "user", content: { type: "image_url", image_url: { url: "https://example.com/image.jpg" } } }
```

should be

```
    { role: "user", content: [{ type: "image_url", image_url: { url: "https://example.com/image.jpg" } }] }
```

**Comment by nimish-gupta** [comment]
> Looks like you might be missing an array around the second `content` block, i.e.
> 
> ```
>     { role: "user", content: { type: "image_url", image_url: { url: "https://example.com/image.jpg" } } }
> ```
> 
> should be
> 
> ```
>     { role: "user", content: [{ type: "image_url", image_url: { url: "https://example.com/image.jpg" } }] }
> ```

my bad in the issue description, I am sending the array.

**Comment by ankrgyl** [comment]
Can you send an exact repro then? I just tried using the above, and it worked just fine:

```
In [18]: client = OpenAI(base_url='https://api.braintrust.dev/v1/proxy', api_key=os.environ['BRAINTRUST_API_KEY'])

In [19]: client.chat.completions.create(  model="gemini-1.5-flash-latest",
    ...:   messages=[
    ...:     { "role": "user", "content": "What do you think of this image?" },
    ...:     { "role": "user", "content": [{ "type": "image_url", "image_url": {"url": "https://cdn.prod.website-files.com/64949e4863d96e26a1da8386/64f5f56c78d05cf501922f99_64a2ef9774661044d9755e98_URL%2520-%2520Glossary.png" }}] }
    ...:   ],
    ...: )
```

**Comment by nimish-gupta** [comment]
So this is the code that i am using. I am [this](https://github.com/openai/openai-node) open ai node package
```
  const messages = [ {
    role: "user" as const,
    content: [
      {
        type: "image_url" as const,
        image_url: {
          url: "https://cdn.prod.website-files.com/64949e4863d96e26a1da8386/64f5f56c78d05cf501922f99_64a2ef9774661044d9755e98_URL%2520-%2520Glossary.png",
        },
      },
    ],
  }];

  const completion = await client.chat.completions.create({
    model: "gemini-1.5-flash-latest",
    messages,
    logprobs: true,
    temperature: 0,
  });

  console.log(completion);
```

After this i am getting the error:
```
[2024-10-16 12:20:39] ERROR: Unhandled rejection
    err: {
      "type": "BadRequestError",
      "message": "400 Invalid JSON payload received. Unknown name \"text\" at 'contents[0].parts[0]': Proto field is not repeating, cannot start list.",
      "stack":
          Error: 400 Invalid JSON payload received. Unknown name "text" at 'contents[0].parts[0]': Proto field is not repeating, cannot start list.
              at Function.generate (~/node_modules/.pnpm/openai@4.55.4_zod@3.23.8/node_modules/openai/error.js:45:20)
              at OpenAI.makeStatusError (~/node_modules/.pnpm/openai@4.55.4_zod@3.23.8/node_modules/openai/core.js:275:33)
              at OpenAI.makeRequest (~/node_modules/.pnpm/openai@4.55.4_zod@3.23.8/node_modules/openai/core.js:318:30)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "status": 400,
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json; charset=UTF-8",
        "date": "Wed, 16 Oct 2024 06:50:39 GMT",
        "server-timing": "gfet4t7; dur=59",
        "transfer-encoding": "chunked",
        "x-amz-cf-pop": "DEL54-P6",
        "x-amzn-requestid": "b5178772-ad22-4a3d-9379-a2d100e263f0",
        "x-amzn-trace-id": "Root=1-670f623e-7aacdbad3c9efa58021df12b;Parent=63eae876af5b71e1;Sampled=0;Lineage=1:a00f27e0:0",
        "x-bt-cached": "MISS",
        "x-cache": "Error from cloudfront",
        "x-cached": "false",
        "x-content-type-options": "nosniff",
        "x-frame-options": "SAMEORIGIN",
        "x-xss-protection": "0"
      },
      "error": {
        "type": "Object",
        "message": "Invalid JSON payload received. Unknown name \"text\" at 'contents[0].parts[0]': Proto field is not repeating, cannot start list.",
        "stack":

        "code": 400,
        "status": "INVALID_ARGUMENT",
        "details": [
          {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
              {
                "field": "contents[0].parts[0]",
                "description": "Invalid JSON payload received. Unknown name \"text\" at 'contents[0].parts[0]': Proto field is not repeating, cannot start list."
              }
            ]
          }
        ]
      },
      "code": 400
    }
```

**Comment by nimish-gupta** [comment]
> e.g. maybe your API key is going to a different model than mine

Thanks for pointing out to this. I changed to `gemini-1.5-flash` and it starts working.

**Comment by ankrgyl** [comment]
Chatted a bit with the gemini team, and they suggest using `gemini-1.5-pro` and `gemini-1.5-flash` without the `-latest` suffix.
